# Generated by Django 4.2.6 on 2023-11-08 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_delete_tbl_assignstaff'),
        ('Userboutique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_bookingservice',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='tbl_bookingservice',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_addservices'),
        ),
    ]
