# Generated by Django 4.2.6 on 2023-11-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userboutique', '0002_remove_tbl_bookingservice_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_bookingservice',
            name='booked_date',
            field=models.DateField(null=True),
        ),
    ]
