# Generated by Django 4.2.6 on 2023-11-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userboutique', '0003_tbl_bookingservice_booked_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=40)),
                ('blog_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
