# Generated by Django 4.2.6 on 2023-11-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userboutique', '0005_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=33)),
                ('message', models.CharField(max_length=30)),
            ],
        ),
    ]
