# Generated by Django 4.2.6 on 2023-11-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userboutique', '0006_tbl_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_contactus',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
