# Generated by Django 4.2.6 on 2023-10-18 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0004_tbl_typesof'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='Hairstylepic/')),
                ('status', models.CharField(default='0', max_length=1)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_staff')),
                ('typesof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_typesof')),
            ],
        ),
    ]
