# Generated by Django 4.2.6 on 2023-10-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addingstyles',
        ),
    ]
