# Generated by Django 4.2.6 on 2023-10-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0006_tbl_haircuts_tbl_typesofhair'),
        ('Shop', '0004_delete_tbl_addingstyles'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addingstyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='Hairstylepic/')),
                ('typesof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_typesof')),
            ],
        ),
    ]
