# Generated by Django 4.2.6 on 2023-10-26 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_haircoloring_tbl_typesofcoloring'),
        ('Shop', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addinghair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='Haircut/')),
                ('haircut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_haircuts')),
                ('typesofhair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_typesof')),
            ],
        ),
    ]
