# Generated by Django 4.2.6 on 2023-10-30 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_haircoloring_tbl_typesofcoloring'),
        ('Shop', '0007_rename_haircut_tbl_addinghair_haircuts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addingcoloring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='Haircolor/')),
                ('haircoloring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_haircoloring')),
                ('typesofhair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_typesofcoloring')),
            ],
        ),
    ]
