# Generated by Django 4.2.6 on 2023-10-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('dateoj', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
