# Generated by Django 4.2.6 on 2023-10-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_styles'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_typesof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typesof', models.CharField(max_length=35)),
                ('styles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_styles')),
            ],
        ),
    ]
