# Generated by Django 4.2.6 on 2023-10-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_typesof'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='Shoppic/')),
                ('proof', models.FileField(upload_to='Shoppic/')),
            ],
        ),
    ]
