# Generated by Django 4.2.6 on 2023-10-23 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_haircuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haircuts', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_typesofhair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typesofhair', models.CharField(max_length=40)),
                ('haircuts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_haircuts')),
            ],
        ),
    ]
