# Generated by Django 4.2.6 on 2023-10-26 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_haircoloring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haircoloring', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_typesofcoloring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typesofhair', models.CharField(max_length=40)),
                ('haircoloring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_haircoloring')),
            ],
        ),
    ]
