# Generated by Django 4.2.6 on 2023-11-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0009_delete_tbl_admin_delete_tbl_shop_delete_tbl_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_staffreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('doj', models.DateField(auto_now_add=True, null=True)),
                ('image', models.FileField(upload_to='Shoppic/')),
                ('photo', models.FileField(upload_to='Shoppic/')),
            ],
        ),
    ]
