# Generated by Django 4.2.6 on 2023-11-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_typesofservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicestypes', models.CharField(max_length=40)),
            ],
        ),
    ]
