# Generated by Django 4.2.6 on 2023-11-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_typesofservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicesdetail', models.CharField(max_length=40)),
                ('rate', models.CharField(max_length=35)),
                ('image', models.CharField(max_length=40)),
                ('servicestypes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_typesofservices')),
            ],
        ),
    ]
