# Generated by Django 4.2.6 on 2023-11-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_addservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_workgalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdate', models.DateField(auto_now_add=True)),
                ('caption', models.CharField(max_length=40)),
                ('image', models.FileField(upload_to='Workpic/')),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_addservices',
            name='image',
            field=models.FileField(upload_to='Hairstylepic/'),
        ),
    ]
