# Generated by Django 4.2.6 on 2023-11-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_tbl_assignstaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assignstaff',
        ),
    ]
