# Generated by Django 4.2.6 on 2023-11-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userboutique', '0002_remove_tbl_bookingservice_payment_status_and_more'),
        ('Admin', '0016_delete_tbl_assignstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_status', models.IntegerField(default='0')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userboutique.tbl_bookingservice')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_staffreg')),
            ],
        ),
    ]
